apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: ingress-nginx
    name: prometheus-configuration  
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
    scrape_configs:
    - job_name: 'microprofile-metrics-endpoints'

      kubernetes_sd_configs:      
      - role: endpoints

      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_mpmetrics]
        action: keep
        regex: true        

      scrape_interval: 15s
      # metrics_path defaults to '/metrics'
      scheme: http    

      tls_config:
        insecure_skip_verify: true

---        
  